language: python

python:
  - 3.8

# command to run tests
script:
  - ./run_tests.sh


before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq poppler-utils imagemagick tesseract-ocr

sudo: false

install:
  - pip install -r requirements.txt
