language: python

python:
  - 3.7

# command to run tests
script:
  - ./run_tests.sh


before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python3-pip python3-setuptools poppler-utils imagemagick tesseract-ocr
- sudo pip3 install --system --install-option="--install-scripts=/usr/local/bin" stapler

sudo: false

install:
  - pip install stapler
  - pip install -r requirements/base.txt
