version: '3.7'
services:
  app:
    image: eugenci/papermerge:1.4.0.rc1
    build:
      context: .
      dockerfile: app.1.4.0.dockerfile
    container_name: papermerge_app
    ports:
      - "8000:8000"
    links:
      - "db:db"      
    depends_on:
      - db
    networks:
      - djangonetwork       
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/app/queue
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
  db:
    image: postgres:12.3
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
    networks:
      - djangonetwork 
  worker:
    image: eugenci/papermerge-worker:1.4.0.rc1
    build:
      context: .
      dockerfile: worker.1.4.0.dockerfile    
    container_name: papermerge_worker
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/app/queue
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    networks:
      - djangonetwork
volumes:
  postgres_data:
  broker_queue:
  media_root:
networks:
  djangonetwork:
    driver: bridge    

