version: '3.7'
services:
  app:
    image: eugenci/papermerge:1.4.0.rc1
    build:
      context: .
      dockerfile: app.1.4.0.dockerfile
    container_name: papermerge_service
    ports:
      - "8000:8000"
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/broker/queue
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
  worker:
    image: eugenci/papermerge-worker:1.4.0.rc1
    build:
      context: .
      dockerfile: worker.1.4.0.dockerfile    
    container_name: papermerge_worker
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/broker/queue
volumes:
  broker_queue:
  media_root:
